const NICHE_CATEGORIES = {
  "Crypto & Web3": [
    "DeFi",
    "Yield",
    "Stablecoins",
    "RWA",
    "Protocol Growth",
    "Trading",
    "Ethereum",
    "Bitcoin",
    "Security",
    "DAO",
    "L2",
    "AI x Crypto",
    "NFTs",
    "Layer 1",
    "Layer 2",
    "Tokenomics",
    "Mining",
    "Wallets",
    "Payment Rails",
    "Smart Contracts",
  ],
  "Programming & Tech": [
    "Web Development",
    "Mobile Development",
    "AI / Machine Learning",
    "Data Science",
    "DevOps",
    "Cloud Computing",
    "Cybersecurity",
    "Open Source",
    "Game Development",
    "No-Code",
    "SaaS",
    "QA / Testing",
    "API Development",
  ],
  "Design & Creative": [
    "UI/UX Design",
    "Graphic Design",
    "Branding",
    "Illustration",
    "3D Design",
    "Motion Graphics",
    "Photography",
    "Videography",
    "Video Editing",
    "Animation",
    "Typography",
  ],
  "Business & Marketing": [
    "Entrepreneurship",
    "Startups",
    "E-commerce",
    "SEO",
    "Content Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Copywriting",
    "Advertising",
    "Personal Branding",
    "Product Management",
    "Growth Hacking",
    "Sales",
    "Affiliate Marketing",
  ],
  "Finance & Investing": [
    "Stock Market",
    "Personal Finance",
    "Real Estate",
    "Wealth Management",
    "Accounting",
    "Tax",
    "Insurance",
    "Venture Capital",
    "Angel Investing",
    "Financial Planning",
  ],
  "Science & Education": [
    "Physics",
    "Biology",
    "Chemistry",
    "Mathematics",
    "Astronomy",
    "Environmental Science",
    "Research",
    "Online Education",
    "Language Learning",
    "Academic Writing",
    "Science Communication",
  ],
  "Agriculture & Environment": [
    "Farming",
    "Sustainable Agriculture",
    "Climate Action",
    "Renewable Energy",
    "Food Security",
    "Forestry",
    "Wildlife Conservation",
  ],
  "Food & Lifestyle": [
    "Cooking",
    "Baking",
    "Recipe Development",
    "Food Review",
    "Restaurant Culture",
    "Nutrition",
    "Meal Prep",
    "Veganism",
  ],
  "Health & Wellness": [
    "Fitness",
    "Mental Health",
    "Self-Improvement",
    "Productivity",
    "Biohacking",
    "Yoga",
    "Meditation",
    "Women's Health",
    "Men's Health",
    "Public Health",
  ],
  "Creative Writing & Media": [
    "Podcasting",
    "Book Reviews",
    "Poetry",
    "Creative Writing",
    "Journalism",
    "Screenwriting",
    "Music Production",
    "Music Reviews",
    "Film",
    "Anime",
  ],
  "Professional Services": [
    "Virtual Assistance",
    "Freelancing",
    "Career Development",
    "Legal",
    "Recruiting",
    "Remote Work",
    "Outsourcing",
  ],
  "Travel & Culture": [
    "Travel",
    "Digital Nomad",
    "Cultural Commentary",
    "Language & Translation",
    "Expats",
  ],
  "Sports & Entertainment": [
    "Esports",
    "MMA / Boxing",
    "Football",
    "Basketball",
    "Gaming",
    "Streaming",
    "Comedy",
  ],
  "Social Impact": [
    "Philanthropy",
    "Social Justice",
    "Community Building",
    "Nonprofit",
    "Activism",
  ],
  "Other": [
    "Parenting",
    "Pets / Animals",
    "Architecture",
    "Construction",
    "Interior Design",
    "Fashion",
    "Politics",
    "Memes / Humor",
    "Books / Reading",
  ],
} as const;

export type Niche = (typeof allNiches)[number];

export const allNiches: string[] = Object.values(NICHE_CATEGORIES).flat();

export const nicheCategories = NICHE_CATEGORIES;
